// This file is automatically generated. Do not edit it directly.

import { createMiddleware } from "@tanstack/react-start";
import { getRequest } from "@tanstack/react-start/server";
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

function isNewSupabaseApiKey(value: string): boolean {
  return (
    value.startsWith("sb_publishable_") ||
    value.startsWith("sb_secret_")
  );
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request
        ? input.headers
        : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => {
        headers.set(key, value);
      });
    }

    // With the new sb_publishable_* keys, the key belongs
    // in the apikey header, not as the user's Authorization token.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);

    return fetch(input, {
      ...init,
      headers,
    });
  };
}

export const requireSupabaseAuth = createMiddleware({
  type: "function",
}).server(async ({ next }) => {
  const SUPABASE_URL = process.env["SUPABASE_URL"];
  const SUPABASE_PUBLISHABLE_KEY =
    process.env["SUPABASE_PUBLISHABLE_KEY"];

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    throw new Error(
      "Supabase server environment variables are missing.",
    );
  }

  const request = getRequest();

  const authHeader = request.headers.get("authorization");

  if (!authHeader) {
    throw new Error("Missing authorization header.");
  }

  if (!authHeader.toLowerCase().startsWith("bearer ")) {
    throw new Error("Invalid authorization header.");
  }

  const token = authHeader.slice(7).trim();

  if (!token) {
    throw new Error("Missing access token.");
  }

  /*
   * ---------------------------------------------------------
   * CLIENT 1: AUTH VALIDATION
   * ---------------------------------------------------------
   *
   * This client does NOT use accessToken.
   * Therefore auth.getClaims() is allowed.
   */
  const authClient = createClient<Database>(
    SUPABASE_URL,
    SUPABASE_PUBLISHABLE_KEY,
    {
      global: {
        fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
      },
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
      },
    },
  );

  const { data: claimsData, error: claimsError } =
    await authClient.auth.getClaims(token);

  if (claimsError || !claimsData?.claims?.sub) {
    console.error("[SUPABASE AUTH ERROR]", {
      message: claimsError?.message,
    });

    throw new Error("Invalid authentication token.");
  }

  const userId = claimsData.claims.sub;

  /*
   * ---------------------------------------------------------
   * CLIENT 2: DATABASE / RLS
   * ---------------------------------------------------------
   *
   * This client uses accessToken so Supabase/PostgREST
   * executes queries as the authenticated user.
   *
   * IMPORTANT:
   * Do NOT call supabase.auth.getClaims() on this client.
   */
  const supabase = createClient<Database>(
    SUPABASE_URL,
    SUPABASE_PUBLISHABLE_KEY,
    {
      accessToken: async () => token,

      global: {
        fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
      },

      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
      },
    },
  );

  console.log("[SUPABASE SERVER CONFIG]", {
    url: SUPABASE_URL,
    keyPrefix: SUPABASE_PUBLISHABLE_KEY.slice(0, 18),
  });

  console.log("[SUPABASE JWT CLAIMS]", {
    sub: userId,
    role: claimsData.claims.role,
    aud: claimsData.claims.aud,
    iss: claimsData.claims.iss,
  });

  return next({
    context: {
      supabase,
      userId,
      claims: claimsData.claims,
    },
  });
});